### ISSUE TITLE
A Sun Tzu Art of War quote grabber

### ISSUE THREAD

**Issue by IceCereal** [IceCereal/RobotSteve#1]
We need a new command for our bot that takes a random The Art of War, Sun Tzu, quote and posts it in the channel it was summoned with `-Technoblade` at the end. A list of quotes can be kept in `res/` to choose the quote from. 

The command: `++quote`
The location of the new file: `utils/random/`

**Comment by wonder-coconut** [comment]
if you wish to defeat me, train for another 500 years

**Comment by IceCereal** [comment]
Would you like to take this up?

**Comment by wonder-coconut** [comment]
yes pls

**Comment by wonder-coconut** [comment]
I'd like to take this up

**Comment by IceCereal** [comment]
Alright, you have the go ahead.

**Comment by IceCereal** [comment]
Solved in #8. Am closing.
