### ISSUE TITLE
A statistic viewer

### ISSUE THREAD

**Issue by IceCereal** [IceCereal/RobotSteve#3]
We need a statistic viewer that tells us the statistics of a user. (Note that this conflicts with the existing ++stats command. This will be changed to ++online)

The command is to be:
`++stats @user` : User statistics
`++stats all` : Global statistics

User statistics should show:

- how many times the user has logged on
- how many hours, minutes, seconds has has the user played
- longest session played
- percentage of time played with respect to total hours played (Elaborated below)
- [Optional] Amount of messages sent
- [Optional] Amount of achievements (if possible achievements also)

Global statistics should show:

- who has the most hours played ranked (top 5)
- who has logged on and off the most amount of times
- longest sessions played
- [Optional] most amount of messages

Percentage of time played with respect to total hours played is explained through this example. If three people are playing on the server and if they have 3 hours, 4 hours and 5 hours played on the server, the first person has  3 / (3+4+5) * 100 % of the time played on the server.

**Comment by AnantaSrikar** [comment]
I'd like to take this up.

**Comment by IceCereal** [comment]
Go ahead 👍
